### ISSUE TITLE
Feedback - Blocked elements not collapsing without reload

### ISSUE THREAD

**Issue by brianmbutler** [el1t/uBlock-Safari#10]
Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue

When loading a new page, the elements (ads) are blocked, but the space they occupied is shown as blank, rather than collapsing/hiding them.  A page refresh will cause them to collapse/hide as expected.

### One or more specific URLs where the issue occurs

http://www.macrumors.com

[URL(s) for issue on a specific site are **mandatory**]

### Screenshot in which the issue can be seen

http://imgur.com/P2YZZRj

[Screenshot(s) for visual issues are **mandatory**]

### Steps for anyone to reproduce the issue

1. Be as detailed as possible:
1. Because we are not looking over your shoulder and
1. Keep in mind: Nobody can read your mind.

### Your settings

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- Safari version:  Technology Preview 19
- uBlock Origin version: 1.10.0 preview 4
- MacOS version: 10.12.1

##### Your filter lists

Default

##### Your custom filters (if any)

None

**Comment by el1t** [comment]
Seems to be caused by Safari's preloading feature, which triggers `onBeforeRequest` prior to navigation.
