### ISSUE TITLE
uBlock Origin Randomly Stops Functioning

### ISSUE THREAD

**Issue by Jack15911** [el1t/uBlock-Safari#100]
> Filter issues **MUST NOT** be reported here. Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue
Over the past several months my uBlock Origin extensions have  stopped working. It can  be brought back to functioning by removing the extension and re-installing. This appears to be at random times and if I'm doing anything to cause it I'm not aware of it.

### One or more specific URLs where the issue occurs
https://www.marketwatch.com, https://www.nytimes.com, plus all other sites I visit.
> [URL(s) for issue on a specific site are **mandatory**]

### Screenshot in which the issue can be seen
<img width="1280" alt="screen shot 2018-03-01 at 5 41 21 pm" src="https://user-images.githubusercontent.com/36242108/36876166-43d29b50-1d79-11e8-99e1-2c416b365a1d.png">
<img width="1280" alt="screen shot 2018-03-01 at 5 40 58 pm" src="https://user-images.githubusercontent.com/36242108/36876167-43e4f87c-1d79-11e8-858a-011c07fe8906.png">
<img width="1280" alt="screen shot 2018-03-01 at 5 28 07 pm" src="https://user-images.githubusercontent.com/36242108/36876168-43f70de6-1d79-11e8-8e35-8b5e6327f503.png">
> [Screenshot(s) for visual issues are **mandatory**]

### Steps for anyone to reproduce the issue
It requires no steps of which I'm aware to reproduce the issue; it has happened approximately five times over the past three months.

The most recent failure is with uBlock Origin 1.15.4. I am running Mac OS 10.13.3 on Safari 11.0.3. My extensions are: uBlock Origin, Disconnect, and Disconnect Private Search. I do clear my Safari cookies daily and cache weekly.

See screen captures. Please note I have selected “I am an advanced user,” but I have not selected any filters beyond the default choices; I use the increased visibility to track what's happening. I have used the Element Picker to select and remove persistent items from web pages (listed below, plus screen capture).

### Your settings
- MacOS version: Mac OS 10.13.3
- Safari version: Safari 11.0.3
- uBlock Origin version: uBlock Origin 1.15.4

##### Your filter lists
Default lists only.

##### Your custom filters (if any)
! 2/16/2018, 10:27:44 AM https://www.nytimes.com/
www.nytimes.com###masthead

! 2/17/2018, 9:36:51 AM https://www.politico.com/story/2018/02/16/muller-indictment-trump-election-legitimacy-416163?lo=ap_b1
||static3.politico.com/resource/images/website/shared/template/bg-noise.24d18bcf9d414e030c36ffd7f30648e8.jpg$image

! 2/17/2018, 9:37:19 AM https://www.politico.com/story/2018/02/16/muller-indictment-trump-election-legitimacy-416163?lo=ap_b1
www.politico.com##.sticky-content.orient-vertical.user-tools

! 2/19/2018, 7:57:46 PM https://www.trade-a-plane.com/filtered/search?category_level1=Single+Engine+Piston&make=PIPER&model=SUPER+CUB&s-type=aircraft
www.trade-a-plane.com###express-currency-top-banner

! 2/20/2018, 5:52:13 PM https://theaviationist.com/
theaviationist.com##.tve-leads-triggered.cnt.bSe.tl-anim-zoom_in.tve-tl-anim.tve_p_lb_content

! 2/20/2018, 5:54:45 PM https://theaviationist.com/newsstand/
theaviationist.com###cookie-law-info-bar

! 2/24/2018, 9:48:50 PM http://www.knivesandstones.com/santoku-all-purpose/?sort=priceasc&page=2
www.knivesandstones.com##.fixed.PageMenu

! 2/25/2018, 7:52:02 AM https://www.arcamax.com/thefunnies/luann/
||vidweb.com/embedcfgpl/779/$subdocument

**Comment by GuitarTab** [comment]
I've experienced random function stops as well, for several weeks, about once or twice daily; also with the new extension gallery version.

> brought back to functioning by removing the extension and re-installing

It's enough to just un- and then re-tick it in Safari prefs, no full deinstallation necessary.

I think it has nothing to do with the site one is visiting.

I'm suspecting (but by no means am I sure) that it might have something to do with clearing Safari's history, which I'm doing often, or with quitting - restarting Safari.

Be that as it may, it's not a real problem, as un-re-ticking only takes a few seconds ...

**Comment by Jack15911** [comment]
Thanks, but parts of uBlock Origin stopped functioning again today, for the third time since I first posted this item. Today Element Picker stopped functioning, though the main blocking functions appeared to continue. Unfortunately, un- and re-tick did not bring Element Picker back, nor did it  work originally for complete function restoration when I tried it prior to making the original report. Complete function today was again restored by un-installing and re-installing the app, then restoring settings from file.

One thing I neglected to mention in the original post was an occasional need to clear Locally Stored cookies from ~/Library/Safari/Databases/  or ~/Library/Safari/LocalStorage/. I performed the former  change perhaps two days ago so I suspect this issue is linked.

**Comment by Jack15911** [comment]
I'm satisfied that the clearing of ~/Library/Safari/Databases/ or ~/Library/Safari/LocalStorage/ in order to clear persistent elements (cookies, pages) causes uBlock Origin to fail, fully or partially and that this Issue was caused by my actions. It can therefore be closed.

**Comment by kode54** [comment]
I experience this issue on a fresh install of 10.13.5, and no manual clearing of local storage has occurred. It just happened today with imgur, and clicking the enable button immediately disabled. It managed to work when I refreshed the page.

**Comment by utopiabound** [comment]
Clearing History also causes this bug.  Disabling and re-enabling resolved it for me also.
