### ISSUE TITLE
uBlock Randomly Disables - Ads displayed on YouTube.com

### ISSUE THREAD

**Issue by elaine-jackson** [el1t/uBlock-Safari#101]
### Describe the issue
At first I thought this was specific to Adblock Plus, I opened an issue with easylist (See: https://github.com/easylist/easylist/issues/937) however the issue has also occurred with uBlock Origin. My adblocker seems to be randomly disabled while using YouTube.com allowing YouTube to display in stream advertisements despite the usage of an adblocker.

### One or more specific URLs where the issue occurs

* https://www.youtube.com/watch?v=dpCMpJ1XX9I&list=RDMMM9bq_alk-sw&index=4

### Screenshot in which the issue can be seen
<img width="1280" alt="screen shot 2018-03-01 at 7 46 53 pm" src="https://user-images.githubusercontent.com/8227641/36878594-b186d396-1d8d-11e8-8338-4dc7a894e100.png">

### Steps for anyone to reproduce the issue

1. Watch a video on YouTube.com
2. Wait for uBlock to bug out and advertisements to display. When the extension is bugged the power button will not let you click it.
3. Profit? In my case sob...

### Your settings
- MacOS version: High Sierra 10.13.3
- Safari version: 11.0.3
- uBlock Origin version: uBlock Origin 1.14.24
<img width="554" alt="screen shot 2018-03-01 at 8 23 13 pm" src="https://user-images.githubusercontent.com/8227641/36878749-6cb0fb24-1d8e-11e8-8b7d-e432fba18f64.png">
[my-ublock-backup_2018-03-01_20.23.20.txt](https://github.com/el1t/uBlock-Safari/files/1773356/my-ublock-backup_2018-03-01_20.23.20.txt)

##### Your filter lists

<img width="1280" alt="screen shot 2018-03-01 at 8 16 05 pm" src="https://user-images.githubusercontent.com/8227641/36878557-8efa424a-1d8d-11e8-9d76-24e77eef101f.png">
<img width="1280" alt="screen shot 2018-03-01 at 8 16 00 pm" src="https://user-images.githubusercontent.com/8227641/36878559-8f21a97a-1d8d-11e8-964f-49e94ac11778.png">
<img width="707" alt="screen shot 2018-03-01 at 8 15 44 pm" src="https://user-images.githubusercontent.com/8227641/36878560-8f44e516-1d8d-11e8-9b98-26c5f992e0c9.png">
<img width="526" alt="screen shot 2018-03-01 at 8 15 34 pm" src="https://user-images.githubusercontent.com/8227641/36878561-8f66edb4-1d8d-11e8-9233-bee3d7bc9c5e.png">
<img width="611" alt="screen shot 2018-03-01 at 8 15 21 pm" src="https://user-images.githubusercontent.com/8227641/36878562-8f8cf4c8-1d8d-11e8-9a19-65f0b182dd5c.png">
<img width="523" alt="screen shot 2018-03-01 at 8 15 06 pm" src="https://user-images.githubusercontent.com/8227641/36878563-8fb3e286-1d8d-11e8-82a6-ad80c5ce26be.png">

**Comment by Baccount** [comment]
1. backup all your settings on the main settings page for ublock.
2. uninstall your current version.
3. install the latest version [here](https://github.com/el1t/uBlock-Safari/releases/download/1.15.4/uBlock0.safariextz) 
4. restore your settings from the backup in step 1.

Or wait until the update comes from the Safari extension store.
@nsuchy

**Comment by kode54** [comment]
I also experienced this with 1.15.4, but I tried again after updating my lists and loading the linked video, and it didn't happen this time.

**Comment by thehonkinggoose** [comment]
@Baccount @kode54 I haven't had the issue recently, although I have my suspicions that YouTube is doing an AB Test and removes security researchers and adblock contributors.

**Comment by kode54** [comment]
I just experienced this issue again today, this time on Slashdot.

**Comment by kode54** [comment]
Experienced what looks like a disable on a static self-hosted image host server. In the console, I saw:

```
ReferenceError: Can't find variable: vAPI
Global Code -- vapi-client.js:647
```

This looks like a browser screw up, since it's somehow undefining a variable right in the middle of the file that declares it.

**Comment by thehonkinggoose** [comment]
@kode54 Nice catch - hopefully a solution is found :|

**Comment by ghost** [comment]
>```ReferenceError: Can't find variable: vAPI```

Looks similar to https://github.com/uBlockOrigin/uBlock-issues/issues/167
