### ISSUE TITLE
rottentomatoes works on Chrome but not Safari

### ISSUE THREAD

**Issue by hoonkai** [el1t/uBlock-Safari#103]
### Describe the issue

Trailers fail to load on Safari, but are fine on Chrome.

### One or more specific URLs where the issue occurs

https://www.rottentomatoes.com/m/dealt
https://www.rottentomatoes.com/m/thor_ragnarok_2017

### Screenshot in which the issue can be seen

![screen shot 2018-03-05 at 10 43 46 pm](https://user-images.githubusercontent.com/14197204/36975708-b2ec880c-20c6-11e8-93bc-94483ea1df95.png)

### Steps for anyone to reproduce the issue

1. https://www.rottentomatoes.com/m/thor_ragnarok_2017
2. Click on trailer

### Your settings
- MacOS version: 10.12.6
- Safari version: 11.0.3
- uBlock Origin version: 1.14.14

##### Your filter lists

Default filter lists

##### Your custom filters (if any)

None

**Comment by aque** [comment]
It seems the EasyList filter `/admanager.$script` is the cause. Try adding this to My Filters:
`@@||mssl.fwmrm.net/p/nbcu_live/AdManager.js$script,domain=www.rottentomatoes.com`.
