### ISSUE TITLE
Question: Safari asked if I wanted the update from the gallery or from the developer

### ISSUE THREAD

**Issue by fgimenezm** [el1t/uBlock-Safari#104]
I checked if there were updates in the safari preferences and saw version 1.15.4 was there so I clicked the "update" button.
Then Safari asked if I wanted the update from the gallery or from the developer and offered 1.14.24 from the gallery or 1.15.4 from the developer.
I selected the developer one but I was wondering what is this all about? Is the gallery version Safari offered the one from this repo or is it "the other one" ?

**Comment by vassudanagunta** [comment]
I don't think 1.15.4 has made it into the gallery yet. But 1.14.24 in the gallery is from this repo. See the recent comments under #69.

**Comment by ruchernchong** [comment]
The gallery and from developer are now from the same person. It is safe to update from any of it. Just choose the one with the higher version.

**Comment by gurkee9** [comment]
If download the ublock origin from safari extension gallery, then is always the version 1.14.24.
you said this is from this repo.

But in the safari extension gallery and safari settings has a wrong name:
Chris Aljoudi/Raymond Hill
![f2638c47-268a-4675-87dd-905904cea802](https://user-images.githubusercontent.com/37416731/37482126-d481aee2-2883-11e8-8173-911162b591f7.jpeg)

but in the url is correct with **el1t**
https://safari-extensions.apple.com/details/?id=com.**el1t**.uBlock-3NU33NW2M3

**Comment by vassudanagunta** [comment]
please read the recent comments under #69

**Comment by gurkee9** [comment]
@vassudanagunta 
I read it.

But fact is, if user download the extension, then comes not this name **Raymond Hill/Ellis Tsung**

this is only optical nature. but the name chris must go.

**Comment by vassudanagunta** [comment]
Then you missed it:

> I think everyone can relax. The extensions gallery has @el1t's latest release. If you click on the "commits to safari since this release" link on that page, you'll see that the developer name has been updated and will be reflected in the next release to the extensions gallery.

**Comment by gurkee9** [comment]
@vassudanagunta 
No this is wrong! Show my image here again.

Chris Aljoudi/Raymond Hil !!!!!!!!!!!!

that's what I meant!

if it were resolved, you would have closed this report a long time ago. but it's still open.

**Comment by vassudanagunta** [comment]
Dude, chill out. [You didn't take the time to read the comments carefully](https://github.com/el1t/uBlock-Safari/commit/25e74f20a9540a60fe86b773cdc8a54f27978f6f), even though this is now the fourth time I've asked you to. I am not the developer. The developer is very busy. He does this for no pay on his spare time which is probably very little. So you should at least take the time to read the situation before complaining about something that is already understood and handled. Yes, you are right, this is confusing for some people. But piling on more complaints isn't going to help, and it's unappreciative of the context.

**Comment by fgimenezm** [comment]
As the original concern has been clarified many times already I see no point in keeping this issue open.

**Comment by gurkee9** [comment]
@vassudanagunta 
Thx for the up vote. But the scrammer has the report closed and deleted.
