### ISSUE TITLE
Issues with Safari 11.1 element blocker

### ISSUE THREAD

**Issue by KelixAU** [el1t/uBlock-Safari#108]
The contextual menu for blocking elements shows as expected but when selected the tool doesn't work. The element selector that usually appears down the bottom right of screen doesn't deploy.

![screenie](https://user-images.githubusercontent.com/8393299/38069770-296f86d6-3329-11e8-96a1-c43fdbff3559.jpg)

This can be reproduced by quitting safari and trying again.

ive installed both githiub and extension gallery versions and its def broken in the latest safari. 

### Your settings

- MacOS version: 10.13.4 Beta (17E197a)
- Safari version: 13605.1.33.1.2
- uBlock Origin version: 1.15.4

**Comment by ghost** [comment]
On 10.3.3 and the latest Safari Tech Preview, it still works as it should.  Maybe see if you can reproduce on Safari Tech Preview.  Could be a 10.13.4 issue.

- Release 52 (Safari 11.2, WebKit 13606.1.9.3.1)

**Comment by KelixAU** [comment]
I can confirm this issue only expressed itself in one version of safari and as a result can be closed.
