### ISSUE TITLE
Is the Safari port dead?

### ISSUE THREAD

**Issue by georgeperez** [el1t/uBlock-Safari#130]
### Describe the issue

Is the Safari port project dead? There's been no contributor activity since April 23 and the only pull request is stale. Is the project dead?

### One or more specific URLs where the issue occurs

N/A

### Screenshot in which the issue can be seen

N/A

### Steps for anyone to reproduce the issue

N/A

### Your settings

- MacOS version: 10.14 (18A336e)
- Safari version: 12.0 (14606.1.24.40.1)
- uBlock Origin version: N/A

##### Your filter lists

N/A

**Comment by ykqmain** [comment]
I also want to know.

**Comment by Flenville** [comment]
el1t, the guy behind the safari port, seems to take a break from coding, at least here on GitHub. As far as I understand, most work in the past has been done by him. I wouldn't go as far as saying the port is dead, but its main developer seems at least to be on a break. So, time to update that Firefox of yours ;) 

![screen shot 2018-07-20 at 13 05 59](https://user-images.githubusercontent.com/41474281/42999702-20fffb9e-8c1f-11e8-971a-285e203f5051.png)

**Comment by vassudanagunta** [comment]
Yes, clearly @el1t has a life besides this project. I hope he is happy!

There are other issues such as #124. Apple makes it hard to do open source Safari Extensions. 

But perhaps the key thing is this discussion: #112. I'd love for both @el1t and @gorhill to give us their thoughts.

**Comment by georgeperez** [comment]
@Flenville Yeah I noticed that when I read the release notes for the latest version (which is broken, unfortunately). That's mainly why I asked, since the issue of uBlock whitelisted/blacklisted states being permanently stuck on one setting after whitelisting/blacklisting a site quickly came up in the issues page but no hot fix came.

(To better explain the issue, if you were on a site that you whitelisted and then go to a blacklisted site that site would be whitelisted instead, or vice versa by going to a site that has its elements blocked and then when you go to a website that should be whitelisted but had its elements blocked)

I would update my Firefox if it worked on Mojave at the moment! Currently crashing on launch. I'm using a Safari Content Blocker for the time being.

**Comment by Freida-Moo-Goo-Gai-Pan** [comment]
Suddenly the current port doesn't block disqus comments for me anymore, pages load slower, etc... I finally went back to AdGuard. 

The Chrome version still works perfectly fine, but I prefer Safari.

**Comment by ykqmain** [comment]
If this project stops maintenance, I will choose AdGuard instead of changing the browser. Safari is easy to sync between macOS and iOS, I also have Chrome as the second browser.

**Comment by rnemec** [comment]
Are there any forks that seem to pick up the good work?

**Comment by vassudanagunta** [comment]
@gorhill only [links to this one](https://github.com/gorhill/uBlock).  I doubt there are any others, as I don't think it is easy work, it is a thankless job (people only complain, even though the maintainer is doing the work for free, with no help from any of the complainers), and Apple makes it even harder by requiring Developer Program membership (perhaps for good reason, I'm just stating fact).

**Comment by LesterJitsi** [comment]
@vassudanagunta That's exactly what I think too. I'd just say that letting us know the port is dead would be much easier work.

**Comment by michael1900** [comment]
Why no more release? Alternatives?

**Comment by giusr** [comment]
A simple update from @el1t would be nice, if i understand it correctly there are two options: go the extension route or abandon the project. If all content blocking is restricted to the new "apple" model there is no future for ublock on safari. To cram all block lists into content blocker extensions is unreasonable, especially because alot of the features are not available in blocker extensions.

**Comment by NeXrom** [comment]
Nothing new, sad sad

**Comment by adrianmihalko** [comment]
What is the best alternative?

**Comment by NeXrom** [comment]
AdGuard

**Comment by Vertux** [comment]
@NeXrom 

> AdGuard

Thats no alternative, that's just a very commercial product - I would be happy to support uBlock if it would keep the project alive, but not  a product like AdGuard.

**Comment by adrianmihalko** [comment]
I keep uBlock Origin. It does not slows down browser, it's just a warning.

**Comment by freediverx** [comment]
Next year’s MacOS update will kill it for good.

**Comment by monster4lif** [comment]
I for one would be willing to donate to keep getting updates. Maybe it would be worth setting up a GoFund or something of the sort, so the dev can afford to spend more time on it?

**Comment by mega-3000** [comment]
would also donate happily.

**Comment by sporkman** [comment]
I'll give $40.

**Comment by tohuw** [comment]
I'd also donate. The extension no longer properly functions for me (when I switch tabs, references from the previous tab appear in the advanced window, and some settings don't lock in when clicking the lock icon). I'm not going to bother opening new issues for these given what's discussed here, but I would donate to a revival of efforts on this project.
