### ISSUE TITLE
Safari warning, This extension will slow down your web browsing

### ISSUE THREAD

**Issue by pavankjadda** [el1t/uBlock-Safari#133]
### Describe the issue
I recently upgraded to mac OS Mojave. Safari shows "**This extension will slow down your web browsing**" warning right next to uBlock Origin plugin. It's the not case with uBlock plugin. Is this something I should worry about?

### One or more specific URLs where the issue occurs
All websites 
### Screenshot in which the issue can be seen
<img width="782" alt="screen shot 2018-08-03 at 10 16 18 pm" src="https://user-images.githubusercontent.com/17564080/43671609-2fead80c-976b-11e8-8794-2ff69e21e6f3.png">

### Steps for anyone to reproduce the issue

1. Open Safari preferences 
2. Click on Extensions tab then uBlock Origin plugin

### Your settings

- MacOS version: 10.14
- Safari version: 12.0
- uBlock Origin version: 1.16.0

##### Your filter lists

Default filter lists 

##### Your custom filters (if any)

**Comment by georgeperez** [comment]
Delete the uBlock plugin (as well as uBlock Safari icon). It's doesn't have anything to do with this product.

Also, it won't slow down your computing but it will take some computing time to block all those things. So basically, yes it'll slow down your computer in the same way that opening Finder will make it slower. The reason the warning is there is because Mojave will be deprecating Safari Extensions in favor of Safari App Extensions which are bundled with the app.

**Comment by pavankjadda** [comment]
I deleted those immediately, attached in the screenshot just to highlight warning message from uBlock Origin. I didn't know Mojave will be depreciating Safari Extensions, thanks for clarifying that. Do authors of uBlock origin have any plans to update this to App extension?

**Comment by freediverx** [comment]
“Updating the app extension” for Mojave would entail creating a macOS app for uBock Origin. Not sure of the devs have the skillset or the appetite for that.

**Comment by georgeperez** [comment]
We don't know. It was asked in #124 but the maintainer hasn't made any contributions since April 23rd of this year. I asked about it in #130. I think this extension in its current form will not exist for long come macOS Mojave.

**Comment by 0jay** [comment]
One question would be does it actually have an impact on browser speed/function? If not it can be safely used until a solution or alternative is available.

**Comment by ahmetasabanci** [comment]
I've tried re-activating the extension but even though it shows active it doesn't work and power button in the extension always looks grey and does not turn blue. I think we need either original developer to come back or someone else to fork it. Otherwise, it'll turn obsolete real soon.

**Comment by joshorr** [comment]
The extension still works fine currently after re-enabling it in Mac OS 10.13.6 on Safari 12.
