### ISSUE TITLE
Safari auto disabling uBlock due to perceived performance issues.

### ISSUE THREAD

**Issue by popeofnope** [el1t/uBlock-Safari#138]
### Describe the issue

After an update to Safari today and subsequent relaunch of the app, I was greeted with an alert that uBlock would be disabled due to the extension "slowing" my browsing experience. I had to go into the extensions list to reactivate the extension. In the extensions screen, there's also an alert regarding performance, "This extension will slow down your web browsing."

### One or more specific URLs where the issue occurs

N/A

### Screenshot in which the issue can be seen

https://imgur.com/a/pbMMXKX

### Steps for anyone to reproduce the issue

1. Run Updates in App Store to bring Safari up to v12.0
2. Relaunch Safari
3. Alert will pop showing uBlock is disabled due to performance issues.
4. When reactivating uBlock in Preferences>Extensions you will see another alert regarding performance.

### Your settings

- MacOS version: 10.13.6
- Safari version: 12.0
- uBlock Origin version: 1.16.0

##### Your filter lists

N/A

##### Your custom filters (if any)

N/A

**Comment by joel-daros** [comment]
There is a related issue: https://github.com/el1t/uBlock-Safari/issues/133

**Comment by popeofnope** [comment]
See #124 and #130. Closing this one.
