### ISSUE TITLE
Can't Ctrl+Click On/Off Button

### ISSUE THREAD

**Issue by RobFreiburger** [el1t/uBlock-Safari#15]
### Describe the issue
Since Ctrl+Click is bound as a global shortcut for right-click, one cannot ctrl+click the on/off button to unblock/block a specific page.

### One or more specific URLs where the issue occurs
http://google.com

### Screenshot in which the issue can be seen
Not applicable

### Steps for anyone to reproduce the issue
1. Visit website.
2. Open main uBlock Origin UI.
3. Hold Ctrl button.
4. Click on/off button.

### Your settings
- Safari version: 10.0.2
- uBlock Origin version: 1.10.2
- MacOS version: 10.12.2

##### Your filter lists
Not applicable

##### Your custom filters (if any)
Not applicable

**Comment by Snapy** [comment]
On Mac it's <kbd>⌘ cmd</kbd> + <kbd>click</kbd>.
