### ISSUE TITLE
Not possible to install the extension for Safari 13.0

### ISSUE THREAD

**Issue by drrost** [el1t/uBlock-Safari#159]
### Issue description
Not possible to install the extension for Safari 13.0.

### Screenshot

<img width="532" alt="image" src="https://user-images.githubusercontent.com/2144153/65320763-42e97f00-dbab-11e9-8951-4a74f362c993.png">

### Environment

- MacOS version: 10.14.16
- Safari version: 13.0
- uBlock Origin version: 1.16.0

**Comment by alvarnell** [comment]
Yes, that is well known and apparently cannot be fixed.

See this posting from earlier today: https://github.com/el1t/uBlock-Safari/issues/158

**Comment by drrost** [comment]
Oh, many thanks!
