### ISSUE TITLE
uBlock Origin not compatible with Safari 13.0

### ISSUE THREAD

**Issue by ivan-avalos** [el1t/uBlock-Safari#160]
### Describe the issue
uBlock is not compatible with the new version of Safari.

### Steps for anyone to reproduce the issue
Click in the update button in macOS, it will update both macOS and Safari, then, open Safari and notice that a warning will appear saying "Some extensions are not compatible", and the uBlock icon will disappear.

### Your settings

- MacOS version: 10.14.6
- Safari version: 13.0
- uBlock Origin version: latest stable.

**Comment by RaitoBezarius** [comment]
This might be the answer: https://github.com/el1t/uBlock-Safari/issues/158

**Comment by ivan-avalos** [comment]
No way! uBlock Origin is the best ad blocker and Safari my preferred browser! I don't want to migrate to a different browser! But you, fucking Safari, I might get rid of you anyway!

**Comment by vassudanagunta** [comment]
@ivan-avalos 

> But you, fucking Safari, I might get rid of you anyway!

That's a rather uninformed reaction. There are good reasons that Apple is doing this. It's fair to disagree, and if you prefer the full control over the risk, your best option is Firefox. 

HackerNews has a good discussion of the pros and cons: https://news.ycombinator.com/item?id=21025252

**Comment by ivan-avalos** [comment]
Yeah, sorry for the reaction. And I immediately migrated to Firefox after writing this issue.
