### ISSUE TITLE
No longer support Safari 13

### ISSUE THREAD

**Issue by kid1412621** [el1t/uBlock-Safari#161]
### Your settings

- MacOS version: 10.14
- Safari version: 13
- uBlock Origin version: latest

**Comment by ibruzg** [comment]
Sad
https://github.com/gorhill/uBlock/commit/149b5cf59cc760fa98c9753f4b4ec12d4b884d9a

**Comment by ArtemBernatskyy** [comment]
Does this mean that uBlockOrigin will no longer support Safari ? Thx

**Comment by alvarnell** [comment]
Please see [#158](https://github.com/el1t/uBlock-Safari/issues/158)

**Comment by vassudanagunta** [comment]
There are good reasons why Apple changed how Safari works in a way that breaks uBlock Origin.  

HackerNews has a good discussion of the pros and cons of Apple's philosophy: https://news.ycombinator.com/item?id=21025252

It's fair to disagree, and if you prefer the full control over the risk, your best option is Firefox.  Chrome will soon also no longer support uBlock Origin.

**Comment by wuuuluojun** [comment]
Could you update when you are free?

**Comment by alvarnell** [comment]
@wuuuluojun, If you are referring to the developer, no, it's not going to be updated. You need to find an different solution.

**Comment by wuuuluojun** [comment]
> @wuuuluojun, If you are referring to the developer, no, it's not going to be updated. You need to find an different solution.

What a pity , howeven many thanks.

**Comment by vdedyukhin** [comment]
Many still uses Safari 12, including me. I believe one last release will do no harm.

**Comment by RockyMM** [comment]
Should be closed, as the explanation is given in #158
