### ISSUE TITLE
uBlock Origin returns to Safari? 

### ISSUE THREAD

**Issue by cluegithub** [el1t/uBlock-Safari#163]
Apple announced at WWDC they're adding support for the WebExtensions API to macOS Big Sur, so does this mean there's a path for uBlock0's resurrection? I'm not a dev so I don't know the specifics but as a former uBlock0 user that got burned by macOS ~Vista~ Catalina I'd love to see it come back since none of the alternatives have been able to match uBlock0's experience for me, so that announcement seemed promising to me.

**Comment by ghost** [comment]
https://github.com/el1t/uBlock-Safari/issues/158#issuecomment-647813543
