### ISSUE TITLE
iPhone support

### ISSUE THREAD

**Issue by elaine-jackson** [el1t/uBlock-Safari#167]
Now that Apple has enabled support for Safari extensions in Safari for iOS 15 will this extension be submitted to the iOS App Store?

**Comment by ludiofines** [comment]
I would also wish such a feature. Any hints from the maintainers?

**Comment by thehonkinggoose** [comment]
I don't think the main uBlock origin has plans to do this.

**Comment by strafe** [comment]
This extension is abandoned and uses the deprecated extension format (safariextz). Only Safari App Extensions are compatible with Safari 13+ on macOS and any version on iOS.
