### ISSUE TITLE
Can't restore extension settings from file

### ISSUE THREAD

**Issue by ladygin-me** [el1t/uBlock-Safari#17]
### Describe the issue
Click restore from file button and nothing happen after confirmation

### Screenshot in which the issue can be seen

![ScreenShot](http://i.imgur.com/vpt1UP3.jpg)

### Your settings

- Safari 10 TP 20
- uBlock Origin version: 1.10.2.b0 & last 1.10.5.6 merged from gorhill/uBlock source
- MacOS version: Sierra 10.12.2

**Comment by el1t** [comment]
Problem was `safari.extension.settings.clear()` doesn't take a callback, so now it's called manually.
