### ISSUE TITLE
Fix issues listed in chrisaljoudi/uBlock

### ISSUE THREAD

**Issue by el1t** [el1t/uBlock-Safari#2]
There are a number of Safari-related issues that were patched in uBlock but not in uBlock-Origin. These need to be checked and if applicable, merged.
- [x] Distinguish cache from settings storage a7716ddc181f7a84532eb7ec6c0d84d47f77dfbf
- [x] Improve Youtube ad blocking add9739c1b7c16eb60ae8b193ce197e5b4e0136f
- [x] Popup menu improvements 65c35dfa74b1ec572d8f49d74890e47da15ce036

**Comment by gorhill** [comment]
One of the key changes was to use different storages for cached data and user settings.

Introduced recently, uBO uses `vAPI.cacheStorage` for cached data (things that can be trashed without losing precious user setttings), and `vAPI.storage` for precious user settings. `vAPI.cacheStorage` has the same API as `vAPI.storage`.

The `vAPI.cacheStorage` was needed for the MS Edge port (<https://github.com/nikrolls/uBlock-Edge/pull/22>), and was just a good abstraction in general, cached data should not be mixed with permanent data.
