### ISSUE TITLE
Not blocking Google Analytics

### ISSUE THREAD

**Issue by Coriou** [el1t/uBlock-Safari#20]
### The issue

Not so long ago, Ublock was blocking Google Analytics tracker, provided you selected a filter for it of course. Right now, even with the proper filter(s) selected, Google Analytics still operates. Funny thing is, Ublock detects it and tells me it was blocked. When I visit sites I control, I can see all my data is being reported to GA, even though Ublock tells me GA is blocked..

### How to reproduce

To test it, you need to activate a tracking filter and you'll have to visit a site you control with GA installed on it. Just go to the live dashboard of GA and then browse your site. You will see GA reporting your browsing activity and Ublock reporting GA was blocked.

### Additional details

I have selected all of the "confidentiality" filters :

![confidentiality-filters](https://i.imgur.com/UEwdlWM.png)

Ublock says it has blocked the GA script :

![ga-blocked](https://i.imgur.com/qcS6BE7.png)

### My environment

- Safari version: 10.0.2
- uBlock Origin version: 1.10.5.9
- MacOS version: 10.12.2

### My filters

![my-filters](https://i.imgur.com/JYDA7j3.png)

**Comment by el1t** [comment]
It was supposed to be redirected (`<<`), but the functionality wasn't there.
