### ISSUE TITLE
Dropbox: can't download folder

### ISSUE THREAD

**Issue by username1290** [el1t/uBlock-Safari#21]
Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue
Hi, ublock has to be disabled to be able to download a folder.

### One or more specific URLs where the issue occurs
any folder in your dropbox

### Screenshot in which the issue can be seen
couldn't take one, the loading bar flashed too fast

### Steps for anyone to reproduce the issue

1.- Visit dropbox.com **with ublock enabled**
2.- select a folder with some files
3.- click Download
4.- **Result: nothing happens**
5.- Disable ublock
6.- refresh website
7.- select folder, click download
8.- download starts.

### Your settings

- Safari version: Version 10.0.2 (10602.3.12.0.1)
- uBlock Origin version:  1.10.0
- MacOS version: Yosemite 10.10.5 (14F2109)

Custom safari settings:
**Allow Webgl: Disabled
Allow plugins: Disabled**

##### Your filter lists
Parse and enforce cosmetic filters: Checked
Ignore generic cosmetic filters: Checked

**also Checked:**
uBlock filters‎
uBlock filters – Badware risks‎ 
uBlock filters – Privacy‎
uBlock filters – Unbreak‎
Adblock Warning Removal List‎ (forums.lanik.us)
Anti-Adblock Killer | Reek‎ (github.com
EasyList ‎(forums.lanik.us)
EasyPrivacy‎ (forums.lanik.us):
Fanboy’s Annoyance List‎ (forums.lanik.us): 

##### Your custom filters (if any)
none

**Comment by georgeperez** [comment]
Not seeing that on my install. [Link to screenshot](https://www.dropbox.com/s/ajkxlcr4gxhkwpn/Screen%20Shot%202017-01-19%20at%201.33.22%20PM.png).

* Safari version: Version 10.0.2 (12602.3.12.0.1)
* uBlock Origin version: v1.10.5.9
* macOS version: Sierra 10.12.2 (16C67)

From the looks of it, you're running an out-of-date version of uBlock Origin. Try updating?

**Comment by username1290** [comment]
Tried again with updated to 1.10.5.9.

1.- Opened dropbox.com with uBlock activated 
2.- Closed safari with dropbox.com tab opened
3.- Opened safari, restores previous tabs (dropbox, etc.)
4.- Selected folder, clicked on Download,
5.-Folder doesn't download.

**Comment by username1290** [comment]
hm, now it works:
6.- Refreshed the tab
7.- Clicked download, 
8.- Download starts.

Maybe Safari doesn't really refresh the tab

**Comment by el1t** [comment]
Quitting and restarting Safari might be triggering issue #13 (refreshing will fix it)

**Comment by username1290** [comment]
Ohh, that must be it, thanks a million!
