### ISSUE TITLE
cosmetic filters / placeholders

### ISSUE THREAD

**Issue by grgr12** [el1t/uBlock-Safari#24]
With 1.10.7, cosmetic filters do not work properly on SPIEGEL.DE. Many placeholders with text "ANZEIGE". 

edit: The issue is not safari-specific, same placeholders with firefox. So may be not the proper place for this ticket. 

![screen shot 2017-02-04 at 11 02 38](https://cloud.githubusercontent.com/assets/25546620/22617621/daadbf02-eac9-11e6-8ce8-c4cebe7cc44b.png)

**Comment by gorhill** [comment]
I don't see placeholder if not using _"DEU: EasyList Germany"_. So a filter list issue, report to maintainers.

**Comment by gorhill** [comment]
For some reasons, `adition.com` is whitelisted in EasyList Germany. A filter such as `||adition.com^$important,domain=spiegel.de` will force-block it again, and the placehoders disappear (and page loads much faster too). You need to inquire from EasyList Germany authors: <https://forums.lanik.us/viewforum.php?f=90>.

**Comment by grgr12** [comment]
thanks, very helpful info

**Comment by el1t** [comment]
Placeholder gone confirmed, thanks @gorhill! Closing issue.
