### ISSUE TITLE
Pipedrive websites for logged in users not loading

### ISSUE THREAD

**Issue by thomas-kuehn** [el1t/uBlock-Safari#28]
Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue
I am using pipedrive.com and the websites for, e.g. deals view (pipedrive.com/pipeline) and activities (pipedrive.com/activities) are not loading at all. It seems there are loading forever, meaning not to load at all.

### One or more specific URLs where the issue occurs
pipedrive.com/pipeline (you have to be a logged as a user to see this)
pipedrive.com/activities (you have to be a logged as a user to see this)

### Screenshot in which the issue can be seen
-

### Steps for anyone to reproduce the issue
Try to visit the above mentioned sites. The sites are loading forever. This means they are not loading at all. If I deactivate uBlock they start to work again.

### Your settings
- Safari version: 10.0.3
- uBlock Origin version: 1.11.1b
- MacOS version: 10.12.3

##### Your filter lists
all uBlock filters
Adblock Warning Removal List
Anti-Adblock Killer | Reek
EasyList

Basic tracking list by Disconnect
EasyPrivacy
Fanboy’s Enhanced Tracking List

Malvertising filter list by Disconnect​​​​​
Malware Domain List
Malware domains
Malware filter list by Disconnect​​​​​

Anti-ThirdpartySocial (see warning inside list)
Fanboy’s Annoyance List
Fanboy’s Social Blocking List

hpHosts’ Ad and tracking servers
Peter Lowe’s Ad and tracking server list

DEU: EasyList Germany
EU: Prebake - Filter Obtrusive Cookie Notices
FRA: EasyList Liste FR

+ Block remote fonts 

##### Your custom filters (if any)

**Comment by el1t** [comment]
Problem was the XMLHttpRequest blocking code: it throws an error to prevent the object from entering an invalid state, but in doing so breaks the calling code too. Opening an empty URL seems to fix the issue.
