### ISSUE TITLE
Can't install the extension

### ISSUE THREAD

**Issue by quantumgolem** [el1t/uBlock-Safari#29]
### Describe the issue
Can't install the extension!

### Steps for anyone to reproduce the issue
Here's what happens to me:

1. I download the latest version of the extension, version `1.11.1b`.
2. I double click on `uBlock.safariextz`.
3. I get the **Are you sure you want to install the extension “uBlock Origin”?** message in Safari.
4. I click **Trust.**
5. Right after I do that, I notice that the `uBlock.safariextz` file in my Downloads folder disappears. Strange. It doesn't appear in my trash, either. It's as if someone `rm`ed it. Not only that, the extension does seem to have been installed, but it's not checked yet (i.e. isn't not active!).
6. I click on the checkbox to enable it. I get this message: **Are you sure you trust the extension “uBlock Origin”?**. There are three options: **Move to Trash**, **Cancel,** and **Trust**. Obviously I click **Trust.**
7. Nothing happens. The checkbox is still unchecked. :(

Someone please help me. I can't survive without this extension because I have a lot of custom rules and stuff.

### Your settings
- Safari version: 10.1
- uBlock Origin version: 1.11.1b
- MacOS version: 10.12.3 beta 1

### Additional Information

This _may_ have to do with the fact that I'm running a beta version of macOS Sierra, but I'm not too sure myself.

**Comment by quantumgolem** [comment]
Apparently it works? It seems like uBlock is working for me, even though it's unchecked in settings. Most likely a bug in Safari.

**Comment by el1t** [comment]
Did you try the suggested [troubleshooting](https://github.com/el1t/uBlock-Safari/tree/safari/dist#troubleshooting)? Sometimes Safari requires using keyboard controls to select "trust."

**Comment by quantumgolem** [comment]
@el1t Haha, I didn't know about those troubleshooting steps but I did inadvertently install it like that! But if I run into this issue again, I'll reopen this issue. Thanks a ton.
