### ISSUE TITLE
Busy Overlay/Loading Bar don't update properly

### ISSUE THREAD

**Issue by LRFLEW** [el1t/uBlock-Safari#3]
### Describe the issue

When you perform any action in the "3rd-party filters" tab of settings that causes the "busyOverlay"/loading bar to appear (such as pressing the "Update now" or "Apply changes" buttons), the loading bar doesn't appear, and the overlay doesn't disappear. If I change the tab or refresh, then the loading bar can appear, but it doesn't update without changing the tab or refreshing again. If the action has completed when you change the tab or refresh, then the overlay disappears. This only happens for me with the alpha.1 release, not the previous alpha one.

### Your settings

This is all pretty much the same as what I provided in #1, but I'll put these here for simplicity.

- Safari version: 10.0.1
- uBlock Origin version: 1.10.0-alpha.1
- MacOS version: 10.12.1

**Comment by el1t** [comment]
Sorry, stupid mistake. Fixed.
