### ISSUE TITLE
Extension title bar reads uBlock

### ISSUE THREAD

**Issue by sanchezelton** [el1t/uBlock-Safari#31]
Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue

This is more of a cosmetic issue, but shouldn't the extension render its title as uBlock Origin and not simply uBlock, as was the case in previous releases? The only way to verify it is by either viewing it in the extensions editor or clicking from links the the About tab.

### One or more specific URLs where the issue occurs

All sites.

### Screenshot in which the issue can be seen

![screen shot 2017-03-07 at 11 44 19 pm](https://cloud.githubusercontent.com/assets/3165000/23694718/422860e0-0390-11e7-84a1-e0396666cceb.png)

### Steps for anyone to reproduce the issue

1. Install the extension as per the instructions on GitHub.
2. Open Safari (if not already open).
3. Click on the uBlock Origin button. Check the title bar of the pop-up dialog, which reads 'uBlock' not 'uBlock Origin'.

### Your settings

Default settings.

- Safari version: 10.0.3
- uBlock Origin version: 1.11.1.0
- MacOS version: 10.12.3

##### Your filter lists

Default filter lists.

##### Your custom filters (if any)
None.

**Comment by chohner** [comment]
I can confirm that it reads `uBlock Origin` in Firefox
