### ISSUE TITLE
Incorrectly removed content 

### ISSUE THREAD

**Issue by dimisa-RUAdList** [el1t/uBlock-Safari#32]
Incorrectly removed content due to incorrect use of rules:
$websocket
|blob:$script

For example:
http://www.sibnet.ru > http://i.imgur.com/sRe2xS4.jpg
https://e.mail.ru/messages/inbox/ > http://i.imgur.com/ipnnHiN.jpg

Mac OS 10.9.5 (13F1911)
Safari 9.1.3 (9537.86.7.8)
uBlock Origin v1.11.3b1 (Default filter + RU AdList)

**Comment by giveup** [comment]
Have you tried the uBo on chrome or firefox？This is not necessarily a problem with uBlock-Safari.
Generally, This is a issue of adlist.
Sorry for my bad english.

**Comment by dimisa-RUAdList** [comment]
I am a maintainer RU AdList filters. And I check the work of rules and extensions in all browsers:
https://hg.adblockplus.org/ruadlist/shortlog

Incorrect use of the specified syntax in uBlock-Safari is observed since the version 1.10.2b0.

**Comment by gorhill** [comment]
Not sure, but I think the Safari-specific code is blocking inline-script whenever a response header is returned, even if the response header returned was to block something else than inline scripts. It should probably use a regex to find out whether the `script-src` is present, and if not ignore the response (unless it can deal with it).

**Comment by el1t** [comment]
@gorhill that was it! I'll add the check; the only issue is that the logger will still report that it's blocking worker/websocket requests.

**Comment by dimisa-RUAdList** [comment]
Unfortunately, fix did not solve this problem.

**Comment by el1t** [comment]
@dimisa-RUAdList Would you mind testing 1.12.0? It appears to work for me on 9.1.3 (and 10.1)
![screenshot](https://cloud.githubusercontent.com/assets/5885378/24847924/33fcd08e-1d92-11e7-8569-44d6b5a4a3e0.png)

**Comment by dimisa-RUAdList** [comment]
It seems that everything is in order. At least, on e.mail.ru, stylesheets and scripts are no longer blocked in place of websockets. 

sibnet.ru normally earned even after the first fixation (c933d03).

**Comment by el1t** [comment]
Awesome, I'll close this issue then - let me know if anything new comes up!
