### ISSUE TITLE
Why are the privacy settings all greyed out? (disable hyperlink auditing)

### ISSUE THREAD

**Issue by ghost** [el1t/uBlock-Safari#36]
On the home page there are three privacy settings that can not be checked.

**Comment by el1t** [comment]
Safari doesn't support prefetching, beacons, or WebRTC. It does support `ping`, which I'll look into.

**Comment by el1t** [comment]
Okay it took me a while (zero documentation whatsoever), but I think I figured this out. `ping` is enabled by default, but can actually be disabled through a hidden webkit setting I found inside [WebkitSettings.cpp](https://opensource.apple.com/source/WebKit2/WebKit2-7536.30.1/UIProcess/API/gtk/WebKitSettings.cpp.auto.html):

```sh
defaults write com.apple.Safari com.apple.Safari.ContentPageGroupIdentifier.WebKit2HyperlinkAuditingEnabled -bool false
```

I'll add this to the wiki and link to it inside the extension!

**I recommend everyone to disable it.** (it's used for link tracking and cannot be intercepted by uBlock)

>Edit:
>`defaults write com.apple.Safari WebkitHyperlinkAuditingEnabled -bool false` is not needed, but doesn't affect anything if set.
>You can undo it with `defaults delete com.apple.Safari WebkitHyperlinkAuditingEnabled`.

**Comment by el1t** [comment]
[Wiki page here](https://github.com/el1t/uBlock-Safari/wiki/Disable-hyperlink-auditing-beacon).
