### ISSUE TITLE
uBlock Origin in Safari is preventing me from uploading any photos or video to Facebook

### ISSUE THREAD

**Issue by Fofer** [el1t/uBlock-Safari#37]
### Describe the issue

With uBlock-Origin enabled, I am unable to upload pictures or video to Facebook.  Only by completely whitelisting facebook.com, or disabling uBlock-Origin, am I able to once again upload photos or videos to Facebook.  

### One or more specific URLs where the issue occurs

https://www.facebook.com

### Screenshot in which the issue can be seen

With uBlock-Origin 1.10.2:
http://i.imgur.com/DN6BvUs.png

With uBlock-Origin 1.12.0b:
http://i.imgur.com/stksdkt.png

### Steps for anyone to reproduce the issue

Try to upload photos or video to Facebook, as a status update or a comment on someone else's post.  The upload "hangs."

### Your settings

> [If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- Safari version:  10.1
- uBlock Origin version:  1.10.2 as well as 1.12.0b
- MacOS version:  10.12.4

##### Your filter lists

Default filter lists + Ebates Cash Back Shopping​​

##### Your custom filters (if any)
N/A

**Comment by gorhill** [comment]
It's not a uBlock Origin issue, it's a filter list issue -- solution is simply to force an update of the filter lists: <https://github.com/uBlockOrigin/uAssets/issues/367#issuecomment-293890058>.

Updating filter lists should *always* be the first thing to try. And filter list issues need to be reported to filter list maintainers, not here.

**Comment by el1t** [comment]
Confirmed, forcing an update to EasyPrivacy fixes the issue.

(check by opening logger, `||facebook.com/ajax/*logging` rule blocked the image)
