### ISSUE TITLE
Safari 9 Compatibility (Mavericks)

### ISSUE THREAD

**Issue by asoksevil** [el1t/uBlock-Safari#4]
### Describe the issue

It crashes right after installing it. You have to manually delete it from the extensions folder since it will make Safari crash upon opening.

### One or more specific URLs where the issue occurs

[URL(s) for issue on a specific site are **mandatory**]

### Screenshot in which the issue can be seen

[Screenshot(s) for visual issues are **mandatory**]

### Steps for anyone to reproduce the issue

1. Install on Safari 9 on Mavericks

### Your settings

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- Safari version: 9.1.3
- uBlock Origin version: 1.10.0-alpha.1
- MacOS version: 10.9.5

##### Your filter lists

[Example: "Default filter lists + FRA", or "Default filter lists minus uBlock -- Badware risks"]

**Comment by Foiled56** [comment]
[Heres a quick video explaining how to fix your problem](https://youtu.be/9cu28oIigsY)

**Comment by el1t** [comment]
I've been looking into this, seems like uBlock 0.9.5.2 has a similar issue where it throws an error—it just doesn't crash the browser. Occurs when reading third-party assets that are shipped with the extension (`readRepoCopyAsset`) if the resource is not in cache. Still investigating.

**Comment by asoksevil** [comment]
@el1t Yeah, I've been using 0.9.5.2 for a while and it works pretty well (didn't know it was crashing)

Now that it has been fixed, I'll keep trying it.

Thanks!
