### ISSUE TITLE
[1.12.0b] Significant memory use

### ISSUE THREAD

**Issue by deviantintegral** [el1t/uBlock-Safari#40]
I'm seeing pretty significant memory use with the extension enabled. For example, this morning I opened Safari, disabled ublock in each tab via the toolbar, and left it idle, with:

* Tiny Tiny RSS (self hosted) at the login page
* Fastmail.fm at my inbox
* Gmail at my inbox (very low traffic on this account, a message or two a day)
* Hangouts (again, little traffic)
* A Grafana graph (self hosted, not automatically updating or anything like that)

I then used Chrome for the rest of the day.

Eight hours later (say 1.5 hours of real use), "Safari Networking" is using 2.5GB of memory. Other times, I've seen the gmail tab go into 2+ GB, but I /think/ that's only when the extension is actively filtering.

- Safari version: 10.1 (12603.1.30.0.34)
- uBlock Origin version: 1.12.0b
- MacOS version: 10.12.4

##### Your filter lists

> Complete defaults - haven't touched or customized a thing yet.

Anyways, glad to provide some memory profiles, though I'm not too familiar with JS memory profiling (or Safari extension debugging), so I might need some hand holding.

**Comment by gorhill** [comment]
Did you try the exact same scenario _without_ uBlock installed at all?

**Comment by deviantintegral** [comment]
Yes, I did try it with the extension disabled.

I'm in the process of trying again with just the Gmail tab. It took longer, but over 2 days it started at ~275MB and now is at 570MB, with uBlock installed but whitelisted. I will double check again and report back after disabling.

**Comment by ghost** [comment]
I have had significant memory leaks (in excess of 30gb; nearly all of it compressed, the computer still somehow functioned well,) unrelated to uBlock a couple times over the years. 

I found that a simple clean out of the cache and cookies, and history, solved the issue. Be sure to backup your personal uBlock rules.

**Comment by ghost** [comment]
I forgot to mention, a simple *manual* clean out of the cache, cookies and history. It's more or less a hard reset of the whole browser. You'll need to research the folders location, I cannot remember.

**Comment by deviantintegral** [comment]
Thanks, annoying that Reset Safari isn't comprehensive enough.

It's been another two days, and with the uBlock extension disabled, the single GMail tab is now at 470MB. Not as much as I saw with the extension enabled, but enough to indicate it might not be uBlock's code leaking. I'll try once more with uBlock enabled, and then do a cache clear to see if that changes anything,

**Comment by deviantintegral** [comment]
I just spent a few days using Safari actively, but with no extensions at all, and I finally saw leaks in gmail on their own. Thanks for the help, as it does look like this isn't a uBlock issue.
