### ISSUE TITLE
When there would be a certificate?

### ISSUE THREAD

**Issue by Xardas220** [el1t/uBlock-Safari#44]
Hi,
when there will be a certificate to stop the fact that you must install the uBlock Origin extension every time Safari is terminated?

**Comment by el1t** [comment]
The [latest releases](https://github.com/el1t/uBlock-Safari/releases/latest) are signed, so [installing](https://github.com/el1t/uBlock-Safari/tree/safari/dist#install) those will not require reinstallation. I'm also uploading to the Safari Extension gallery, but I'm kind of in the middle of finals right now, so it may take a bit.

**Comment by Xardas220** [comment]
Okay, thank you for your reply, but there are two certificates. Wich one I must install? And must I install the certificate new when you push a new version wich I install via Extension Builder?

**Comment by el1t** [comment]
You do not need to install either; both are encrypted. These are purely for building, not for installation.

**Comment by Xardas220** [comment]
Okay, but when I close Safari or rightclick and quit Safari I must install uBlock from extension builder again. :/

**Comment by el1t** [comment]
Are you absolutely sure you installed from [this link](https://github.com/el1t/uBlock-Safari/releases/latest)? Installing the `uBlock0.safariextz` file does not require using the extension builder or reinstalling at all. I have tested this.

**Comment by Xardas220** [comment]
Okay, it was my fault. I used the method to clone the git and build my own files with terminal instead of install your extension on it's own. Now it works even when I closed Safari, thank you! :)

**Comment by austrasien** [comment]
Hello, it crashes at installation on Safari Technology Preview Release 32 (Safari 11.0, WebKit 12604.1.23.0.4). I can install it in going through Extension Builder, but not using latest releases...

**Comment by el1t** [comment]
@austrasien please search for related issues instead of commenting on an unrelated one. #50 is probably what you're looking for, and it sounds like TP33 fixes the compatibility issues. Closing to prevent further off-topic discussion.
