### ISSUE TITLE
Is the Settings Gear image Gone?

### ISSUE THREAD

**Issue by aaykut** [el1t/uBlock-Safari#48]
> Filter issues **MUST NOT** be reported here. Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue
Just installed uBlock Origin v1.12.5.100, and it seems the Settings gear image usually found top left is missing?

### One or more specific URLs where the issue occurs
N/A - relevant to extension itself (see screenshot)

### Screenshot in which the issue can be seen
![capturfiles-05-17-2017_09 17](https://cloud.githubusercontent.com/assets/5464592/26790532/5029b202-49d1-11e7-9cb5-cd4869bc6f13.png)

### Steps for anyone to reproduce the issue
Please see included screenshot

### Your settings
MacOS version: Sierra 10.12.5 (16F73)
Safari version: Version 10.1.1 (12603.2.4)
uBlock Origin version: v1.12.5.100

##### Your filter lists
Default filter lists

##### Your custom filters (if any)
! 2017-04-10, 9:14:40 AM https://www.macupdate.com/
www.macupdate.com###bundle-stickyscroll

! 2017-04-15, 3:39:07 PM https://www.macupdate.com/
www.macupdate.com###promo-banner

**Comment by maciejtarmas** [comment]
Looks like it's gone, but you can click anywhere in the black upper bar to open settings.

**Comment by gorhill** [comment]
By design, this issue should be closed. See <https://github.com/gorhill/uBlock/issues/2671#issuecomment-306169169>.

**Comment by aaykut** [comment]
Roger that @gorhill -- closing.

**Comment by bershan2** [comment]
Watch out for another change in [1.13.4](https://github.com/gorhill/uBlock/releases/tag/1.13.4): https://github.com/gorhill/uBlock/issues/2718#issuecomment-310188330
