### ISSUE TITLE
Install crashes Safari TP32

### ISSUE THREAD

**Issue by smlombardi** [el1t/uBlock-Safari#50]
### Describe the issue

Trying to install latest release into Safari Tech preview 32 crashes instantly when I click "Trust".

1. Download latest .safariextz file
2. either double-click or open it in Safari TP 32
3. Click "trust" when prompted

Crash.

- MacOS version: 10.12.5 (16F73)
- Safari version: Release 32 (Safari 11.0, WebKit 12604.1.23.0.4)
- uBlock Origin version: 1.12.5b

**Comment by ghost** [comment]
Same to me. Same OS installed and same Safari Tech Preview. Impossible to install. No problems with Safari 10.1.1

**Comment by SimonAB** [comment]
Same crash here. 
Installation of [v. 1.11.3.1 from Apple's extension gallery](https://safari-extensions.apple.com/details/?id=com.el1t.uBlock-8782JU4WM4) works fine though.

**Comment by smlombardi** [comment]
Thanks, @SimonAB, I never noticed it was on the official site before.

**Comment by MysticalOS** [comment]
Was just coming to report this. I tried updating to new one and crash on install. old version which was already installed is fine.

It's also TP 31 as well not just 32

**Comment by MysticalOS** [comment]
Fixed in TP 33 released today

TP 33 is also Safari 11.0 for 10.12.5. It's got a lot of changes even over 32. It went from 416 (TP32) to 457 on HTML5 standards alone. Regular safari is still 409
