### ISSUE TITLE
Crashes on Facebook when scrolling

### ISSUE THREAD

**Issue by smlombardi** [el1t/uBlock-Safari#54]
With the extension loaded, scrolling the page on Facebook eventually leads to the tab crashing and reloading.

facebook.com

- MacOS version: 10.12.5
- Safari version: Release 33 (Safari 11.0, WebKit 12604.1.25.0.2)
- uBlock Origin version: 1.12.5b

##### Your filter lists

Default filter lists

**Comment by MysticalOS** [comment]
I think i disabled ublock and this was still happening. you sure it's ublock?

**Comment by smlombardi** [comment]
I uninstalled UBlock and it works fine now.
