### ISSUE TITLE
Why is Extension Update URL set to chrismatic.io?

### ISSUE THREAD

**Issue by 100ideas** [el1t/uBlock-Safari#59]
### Describe the issue
The `Extension Updates` key in [`platform/safari/Update.plist`](https://github.com/el1t/uBlock-Safari/blob/master/platform/safari/Update.plist#L17) is set to `https://chrismatic.io/ublock/ublock-latest.safariextz`.

Does uBlock-Safari ping `chrismatic.io` and/or get redirected to `ublock.org` if/when it automatically checks for updates to the extension? Is this desirable?

This section of code was last updated in 2015 so it looks vestigal, but I just would rather not help ublock.org with analytics if I can help it. Thanks.

### One or more specific URLs where the issue occurs
- https://github.com/el1t/uBlock-Safari/blob/master/platform/safari/Update.plist#L17
- https://github.com/gorhill/uBlock/blob/master/platform/safari/Update.plist#L17
- https://github.com/gorhill/uBlock/blob/master/platform/safari/Info.plist#L87

### My Environment
- MacOS 10.12.5
- Safari 10.1.1
- uBlock-Safari 1.12.0

**Comment by larpo** [comment]
My guess is that its a left over from before the origin fork, and since upstream doesn't maintain the safari version they didn't bother to clean up references and links...

**Comment by el1t** [comment]
Good catch—Update.plist isn't actually being used (Info.plist doesn't reference it), but I could remove it to avoid confusion.
