### ISSUE TITLE
Doesn't install on Yosemite

### ISSUE THREAD

**Issue by username1290** [el1t/uBlock-Safari#6]
### Describe the issue
Safari install dialog appears, click "Trust" to continue, but never appears in the extensions pane.

### One or more specific URLs where the issue occurs
https://github.com/el1t/uBlock-Safari/releases/download/1.10.0-alpha.2/uBlock.safariextz

### Screenshot in which the issue can be seen
![screen shot 2016-12-06 at 11 40 09 am](https://cloud.githubusercontent.com/assets/2784323/20938558/c2afe632-bba8-11e6-82d0-31e204436b4e.png)
![screen shot 2016-12-06 at 11 42 10 am](https://cloud.githubusercontent.com/assets/2784323/20938683/4041d768-bba9-11e6-8074-c523366f245e.png)

Tried twice to install, still doesn't appear

### Steps for anyone to reproduce the issue

1. Download latest release (1.10.0-alpha.2)
2. Right click on uBlock.safariextz file, select Open
3. Click Trust on install window

### Your settings

- Safari version: Version 10.0.1 (10602.2.14.0.7)
- uBlock Origin version: 1.10.0-alpha.2
- MacOS version: 10.10.5 (14F2009)

##### Your filter lists
N/A

##### Your custom filters (if any)
N/A

**Comment by qhaine** [comment]
I would give Force Installing a try - check out the first answer on this link:

http://apple.stackexchange.com/questions/214760/force-installing-untrusted-safari-extensions

This technique worked for me even when clicking Trust didn't. :)

**Comment by el1t** [comment]
Could it be that you need to use [keyboard controls](https://discussions.agilebits.com/discussion/57442/safari-extensions-dont-install-but-no-error-message) to hit "trust?"

> 1. Launch **System Preferences** and open the **Keyboard** pane.
> 1. Switch to the **Shortcuts** tab.
> 1. Toggle **All Controls** to selected.
> 1. Re-attempt to install the extension and use the `Tab` key on the keyboard to highlight **Trust**.
> 1. Press the `Space bar` key to press the **Trust** button once selected.

**Comment by qhaine** [comment]
Just wanted to follow up - I made a short and simple video on the force installation process.

https://youtu.be/l6PP_R0V7jk

**Comment by username1290** [comment]
![kkkk](https://cloud.githubusercontent.com/assets/2784323/20946402/c7f9d804-bbc7-11e6-86b1-c58e966ce9c2.JPG)
Ok, whatever the reason, that worked, this is crazy, thanks a lot, I'm still surprised.

**Comment by el1t** [comment]
Great! I'll update the installation instructions before closing this issue.

**Comment by PCheezo** [comment]
Safari does this to me often. you cant mouse click. you have to press tab and hit space to select Trust

**Comment by the-real-tokai** [comment]
I think this might be related to mouse feature enhancement tools like "MagicPrefs" or "BetterTouch". If you disable those then it should work properly with mouse too.

Just mentioning this here in case someone else stumbles over this quirk. 😄

**Comment by toxygen** [comment]
I just want to provide some more information about the issue. The tab/space shortcut installation method worked ok. I'm using SmoothMouse pref plugin, that might be related to the issue.

When starting Safari from terminal, this is the log when extension tries to install but fails silently:

Aug 23 14:29:09  Safari[9462] <Error>: Error: this application, or a library it uses, has passed an invalid numeric value (NaN, or not-a-number) to CoreGraphics API and this value is being ignored.Please fix this problem.
Aug 23 14:29:09  Safari[9462] <Error>: Error: this application, or a library it uses, has passed an invalid numeric value (NaN, or not-a-number) to CoreGraphics API and this value is being ignored.Please fix this problem.
Aug 23 14:29:09  Safari[9462] <Error>: Error: this application, or a library it uses, has passed an invalid numeric value (NaN, or not-a-number) to CoreGraphics API and this value is being ignored.Please fix this problem.
Aug 23 14:29:09  Safari[9462] <Error>: Error: this application, or a library it uses, has passed an invalid numeric value (NaN, or not-a-number) to CoreGraphics API and this value is being ignored.Please fix this problem.
Aug 23 14:29:09  Safari[9462] <Error>: Error: this application, or a library it uses, has passed an invalid numeric value (NaN, or not-a-number) to CoreGraphics API and this value is being ignored.Please fix this problem.
Aug 23 14:29:09  Safari[9462] <Error>: Error: this application, or a library it uses, has passed an invalid numeric value (NaN, or not-a-number) to CoreGraphics API and this value is being ignored.Please fix this problem.
