### ISSUE TITLE
uBlock behaves incorrectly on hltv.org. Not a filter issue.

### ISSUE THREAD

**Issue by ptkovsky** [el1t/uBlock-Safari#65]
Hello. The issue is that uBlock on Safari doesn't seem to block some ads on particular page. Background ad seems gone but most of the banners do persist. Tested with Nightly and Chrome with looks like the same configuration and it correctly hides ads in the above-mentioned case. I've already observed this issue for some time and decided to report it because of the curiosity.

URLs:

https://www.hltv.org

Screenshot:

![screen shot 2017-09-10 at 3 55 34 pm](https://user-images.githubusercontent.com/10148835/30249234-ebc10c40-9640-11e7-9fbc-0327ce8276a4.png)

Steps to reproduce this issue:

I'm just loading the website with the same and almost stock uBlock configuration as in other browsers installed on this machine. I've just added some specific regional filters which do not really matter here. 

Configuration:

Settings are close to default. 

Safari version is 10.1.2
uBlock Origin version is 1.13.11b
MacOS version is 10.12.6

Filters:

Stock with regional ones that are irrelevant in this case.

**Comment by freediverx** [comment]
Some ads will always slip through. It’s an ongoing cat and mouse game. You can kill these ads using the element picker, as shown in the following screenshots:

**Comment by ptkovsky** [comment]
Hi. Thanks for the tip. I'm aware of this functionality. The point of this issue is that it seems that it can be only reproduced in Safari. You don't need to pick and disable any ads in other browsers on this page since they are already hidden there by default. Why doesn't stock filters work? This is an uBlock for Safari issue or kind of Apple API problem, as they always say. Just wondering is there an easy fix for this.

**Comment by freediverx** [comment]
Ah, that’s a different matter entirely. I missed this when reading your original post. I know there are some differences in what Safari does and doesn’t let you do via an extension, so this may be to blame. But I’ll leave I'll it to the developers to provide a better response.

**Comment by grgr12** [comment]
I've got sort of similar issue on spiegel.de (don't want to open a new topic, it seems to be to close to a filter-related area). I get an anti-adblock popup - in Safari only; German filters active; no such issue with equivalent configurations in Firefox and Chrome. 

(posted also here: https://github.com/uBlockOrigin/uAssets/issues/682)

**Comment by ghost** [comment]
It may have something to do with those images and gifs being served by "static.hltv.org" as you can see in the logger.  Probably having trouble discerning the ad content from other 1st party content you would normally allow.

![screen shot 2017-09-10 at 2 43 19 pm](https://user-images.githubusercontent.com/31828312/30251875-8eca8aa2-9636-11e7-97df-3491991047dd.png)

**Comment by dominiklohmann** [comment]
Is there any update on this? Currently, spiegel.de is basically unusable on Safari with an adblocker running.

**Comment by ptkovsky** [comment]
Hi guys. Recently tried to reproduce your spiegel issue and that doesn't seem to come up for me no matter how much I was browsing the site and clicking on any elements. I even tried to open an article or watch a video but no popups appeared for me. Didn't bother with any German VPN shenanigans though but I doubt that that can even matter. I do think that this is a sort of separate issue for you guys that deserves another thread. Looking forward for a smart guy with a mac who can help us with this problems occurring. Cheers.

**Comment by larzon83** [comment]
Hey, have had the same problems with spiegel.de on Safari.
I just clicked the button "Empty Cache storage" in ublock prefs and then on "update now".
Now, the Anti-Adblock Popup doesn't come up anymore :)
![bildschirmfoto 2017-09-21 um 10 31 44](https://user-images.githubusercontent.com/23213583/30686287-16ba6eda-9eb8-11e7-951c-b6037cbd8f4d.png)

**Comment by grgr12** [comment]
For spiegel.de-issue, take a look:
https://github.com/uBlockOrigin/uAssets/issues/682#issuecomment-331240946 

@ptkovsky Excuse me that I started to discuss it in your thread, I was sort of indecisive in light of the "filter-related" restriction

**Comment by ptkovsky** [comment]
So the issue still persists for me even after updating to release 1.14.14.

**Comment by ptkovsky** [comment]
Looks like somewhere around 1.14.24 release this doesn't occur much anymore. Probably can close this issue till it comes again.
