### ISSUE TITLE
Manual Installation Clarification

### ISSUE THREAD

**Issue by chargeflux** [el1t/uBlock-Safari#7]
Regarding this instruction: 
"Clone uBlock-Safari and uAssets into the same parent directory"

Does this mean I would run `git clone` for "UBlock-Safari" and "uAssets" separately in a folder I created like ~/UBlock for example? I wouldn't need to do any merging right?

Essentially after running `git clone`, I would have two separate folders in ~/UBlock - "uBlock-Safari" and "uAssets".

From there I would go and run `./UBlock-Safari/tools/make-safari.sh`. Does the installation script detect the folder "uAssets" even when it is outside the folder "uBlock-Safari"?

**Comment by el1t** [comment]
Good question, this should clear things up:
```sh
git clone https://github.com/uBlockOrigin/uAssets.git
git clone https://github.com/el1t/uBlock-Safari.git
cd uBlock-Safari
./tools/make-safari.sh
```
Directory structure will look like:
```
~/uAssets
~/uBlock-Safari
```
`make-safari.sh` will call `make-assets.sh`, which performs `cp -R ../uAssets/ ...etc` (relative to current path).

**Comment by chargeflux** [comment]
Thanks for the clarification!
