### ISSUE TITLE
Problème d'affichage Site météo france 

### ISSUE THREAD

**Issue by Danielcot38** [el1t/uBlock-Safari#70]
> Filter issues **MUST NOT** be reported here. Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### One or more specific URLs where the issue occurs

> [URL(s)http://www.meteofrance.com/previsions-meteo-france/crolles/38920
### Screenshot in which the issue can be seen

> [Screenshot(s) for visual issues are **mandatory**]

### Steps for anyone to reproduce the issue

1. Be as detailed as possible:
1. Because we are not looking over your shoulder and
1. Keep in mind: Nobody can read your mind.

### Your settings

> [If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- MacOS version: 
- Safari version: 
- uBlock Origin version: 

##### Your filter lists

> [Example: "Default filter lists + FRA", or "Default filter lists minus uBlock -- Badware risks"]

**Comment by el1t** [comment]
Sorry, but there's not enough information here to investigate. Closing for now, please reopen with the required information if the problem persists.
