### ISSUE TITLE
[Safari Technology Preview 11.1] Can't add the extension

### ISSUE THREAD

**Issue by winstonma** [el1t/uBlock-Safari#73]
> Filter issues **MUST NOT** be reported here. Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue
Tried to add unlock on [Safari Technology Preview 11.1](https://developer.apple.com/safari/download/) Release 42 on High Sierra. But error windows pops up saying "an error occurred installing the extension"

### One or more specific URLs where the issue occurs

> [URL(s) for issue on a specific site are **mandatory**]

### Screenshot in which the issue can be seen

> [Screenshot(s) for visual issues are **mandatory**]

### Steps for anyone to reproduce the issue

1. Be as detailed as possible:
1. Because we are not looking over your shoulder and
1. Keep in mind: Nobody can read your mind.

### Your settings

> [If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- MacOS version: 10.13
- Safari version: 11.1
- uBlock Origin version: 1.14.14

##### Your filter lists

> [Example: "Default filter lists + FRA", or "Default filter lists minus uBlock -- Badware risks"]

##### Your custom filters (if any)

**Comment by vassudanagunta** [comment]
Installed no problem for me:

MacOS version: 10.12.6
Safari version: 11.1 (release 42)
uBlock Origin version: 1.14.14

**Comment by winstonma** [comment]
@vassudanagunta as you can see the there are 2 packages available - one for _macOS 10.12.6 or later_ and the other one for _macOS 10.13_. I downloaded the latter one and have this problem.

After further checking, I tried adding other extensions on Safari 11.1 and the extension fails installation process. So I guess it is the Safari 11.1 High Sierra that has the problem.

Thanks @vassudanagunta for testing and helping me find the root cause of the problem.

This ticket will be closed.
