### ISSUE TITLE
Bitcoin mining blocker

### ISSUE THREAD

**Issue by gitguys** [el1t/uBlock-Safari#76]
Does this Safari version of uBlock already block bitcoin mining websites or do I need to set up that manually somehow?  Thank you.

- MacOS version: 10.12.6
- Safari version: 11.0 (12604.1.38.1.7)
- uBlock Origin version: 1.14.14

**Comment by ghost** [comment]
Ensure that "Ublock filters - Resource abuse" is enabled.  I think it is by default but that's the filter list it comes with for this purpose.

**Comment by gitguys** [comment]
Thank you, acasaceli.  Wish they'd make it more obvious.
