### ISSUE TITLE
`:style` and `:inject` commands do not get parsed

### ISSUE THREAD

**Issue by henningko** [el1t/uBlock-Safari#83]
### Describe the issue

I have been trying to override the styles set by the Adblock-blocker on www.spiegel.de 
(`#wrapper-content` gets a `filter: blur(5px); opacity: 0.2`).
I tried `spiegel.de###wrapper-content:style(filter: none !important;)`, however, the filter does not get parsed.
I also tried `spiegel.de##script:inject(setTimeout-defuser.js, adBlockBlocker.check, 1)` which is recommended [here](https://github.com/uBlockOrigin/uAssets/issues/682#issuecomment-328678918), but similarly, the filter does not get parsed.
Blocking `#wrapper-content` causes the website's content to disappear and thus isn't desirable.

### One or more specific URLs where the issue occurs

www.spiegel.de (you need to interact with the websites and adblockers activated to have the anti-adblock modal show up).

### Screenshot in which the issue can be seen

Not a visual issue

### Steps for anyone to reproduce the issue

1. Create filters as outlined above
1. Navigate to www.spiegel.de
1. Interact with website—rules are not applied
1. Navigate to ublock settings → "My filters" does not count added rules that contain `:style` or `:inject`

### Your settings

- MacOS version: 10.13.2
- Safari version: 11.0.2 (13604.4.7.1.3)
- uBlock Origin version: 0.9.5.2

##### Your filter lists

- uBlock, uBlock Privacy
- Adblock Warning Removal
- Anti-Adblock Killer | Reek
- EasyList
- EasyList Germany
- EasyPrivacy
- Fanboy's Enhanced Tracking List
- Malware Domain List
- Malware domains
- Dan Pollock's host file

##### Your custom filters (if any)
`spiegel.de##script:inject(setTimeout-defuser.js, adBlockBlocker.check, 1)`
`spiegel.de###wrapper-content:style(filter: none !important;)`

**Comment by gorhill** [comment]
> uBlock Origin version: 0.9.5.2

Issue is invalid: you are not using uBlock Origin, you are using something else, [an abandonware version](https://github.com/chrisaljoudi/uBlock/graphs/code-frequency).

**Comment by henningko** [comment]
ugh, that's embarrassing (but finally understood the distinction). Closing this.
