### ISSUE TITLE
Unable to install v1.14.14 on Safari

### ISSUE THREAD

**Issue by henrik242** [el1t/uBlock-Safari#85]
I get "Safari can’t install this extension: An error occurred while installing this extension." when trying to install 1.14.14.  I'm on Safari version 11.0.2 (13604.4.7.1.3) and macOS 10.13.2 (17C88).

Older versions fail as well.

![screen shot 2018-01-12 at 19 09 21](https://user-images.githubusercontent.com/129931/34888895-4da1b896-f7cc-11e7-899b-7ee73bd8d98d.png)

**Comment by MysticalOS** [comment]
I'd try installing security update to safari first. They might have sent a cease installation of extensions on safari if it's not security patched yet. They have means to disable things in safari for security reasons (at least with plugins, I'm assuming it applies to extensions too) 10.13.2 (17C205) has an important safari update.

**Comment by henrik242** [comment]
I don't have any outstanding updates as far as I can see.

**Comment by Baccount** [comment]
Run `sudo softwareupdate -i -a` in terminal and it should install any updates.

**Comment by henrik242** [comment]
@Baccount That worked, thanks!
