### ISSUE TITLE
Element Zapper & Element Picker do not work in fresh installation, on stock Safari, on new iMac.

### ISSUE THREAD

**Issue by lukeify** [el1t/uBlock-Safari#88]
### Describe the issue

I install μBlock Origin for Safari on as a matter of habit anytime I do a clean or fresh install of macOS. In this case, I'm setting up my new iMac for the first time. This is stock macOS, stock Safari at the time of writing. 

I followed the standard installation instructions, yet right clicking and selecting "Block Element" does not activate Element Picker mode. 

Neither does explicitly invoking either Element Zapper or Element Picker mode from the extension icon on the Safari toolbar.

### One or more specific URLs where the issue occurs

Appears to be all sites. Tested on irccloud.com, google.com, reddit.com, GitHub.com

### Screenshot in which the issue can be seen

Reproduction of issue in GIF form below.

![2018-01-24 01 53 01](https://user-images.githubusercontent.com/5379845/35276818-8eec4218-00a9-11e8-8dae-4031513baf1f.gif)

![2018-01-24 01 53 50](https://user-images.githubusercontent.com/5379845/35276819-8f19df8e-00a9-11e8-8695-6ce589c60540.gif)

### Steps for anyone to reproduce the issue

1. Installed as per instructions:
  1. Go to Releases page.
  2. Download `uBlock0.safariextz`
  3. Open and Trust in Safari
  4. Optionally restart browser.
2. Attempt to block element using element picker. 

### Your settings

- MacOS version: 10.13.2
- Safari version: Version 11.0.2 (13604.4.7.1.6)
- uBlock Origin version: 11.14.24

##### Your filter lists

Default filter lists.

##### Your custom filters (if any)

None.

**Comment by macvip** [comment]
Just wanted to say I'm having this issue too

**Comment by KelixAU** [comment]
+1 here not working, this is along with no scrolling in 3rd party filters preference pane. 

cant use contextual menu to enable blocking element either

**Comment by KelixAU** [comment]
Cheers mate, how do I build a new version or will one be compiled and uploaded with the 2 new commits?

**Comment by KelixAU** [comment]
Hey Ellis, how’s everything going? 

Is there a more autonomous way the builds can be compiled if you’re too time poor? Ive come to realise how much I reply on the work you’ve done to date and how much I miss it when parts are broken :)
