### ISSUE TITLE
uBlock Origin Safari prevents some websites developed in Angular from loading unless uninstalled

### ISSUE THREAD

**Issue by lukeify** [el1t/uBlock-Safari#89]
### Describe the issue

Been meaning to report this one for a while. Considering I'm here for #88 also, might as well get onto it. uBlock Origin Safari, as of latest version, seems to be prevent some web applications developed in Angular from loading, even when disabled for the site. The extension must be entirely uninstalled for the Angular application to load.

### One or more specific URLs where the issue occurs

https://zefoy.github.io/ngx-dropzone-wrapper/

### Screenshot in which the issue can be seen

![2018-01-24 02 11 15](https://user-images.githubusercontent.com/5379845/35277646-58a2ec68-00ac-11e8-82f8-11e865845926.gif)

### Steps for anyone to reproduce the issue

1. Install uBlock Origin for Safari as per instructions.
2. Visit website using Angular, such as https://zefoy.github.io/ngx-dropzone-wrapper/

### Your settings

- MacOS version: 10.13.2
- Safari version: Version 11.0.2 (13604.4.7.1.6)
- uBlock Origin version: 1.14.24, although not limited to this release.

##### Your filter lists

Default filter lists. Issue is also present when extension is disabled. 

##### Your custom filters (if any)

None.

**Comment by macvip** [comment]
Just wanted to say I'm getting this issue too

**Comment by el1t** [comment]
Figured it out, was setting prototype before binding on `window.Worker`.
